name: data-matching-workflow
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - tqdm
  - networkx
  - simplejson
  - pip
  - pip:
    - recordlinkage
    - dedupe==2.0.2